/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * tunerate-api
 * OpenAPI spec version: 1.0
 */
export interface AlbumDto {
  /** @nullable */
  title?: string | null;
  /** @nullable */
  artist?: string | null;
  artistId?: string;
  /** @nullable */
  releaseDate?: string | null;
  /** @nullable */
  externalId?: string | null;
  /** @nullable */
  coverUrl?: string | null;
}

export interface ReviewDto {
  /** @nullable */
  content?: string | null;
  score?: number;
}

export type GetApiAlbumsParams = {
page?: number;
pageSize?: number;
sort?: string;
genre?: string;
artist?: string;
year?: number;
popularity?: string;
query?: string;
};

export type GetApiAlbumsSearchParams = {
query?: string;
page?: number;
pageSize?: number;
sort?: string;
};

export type GetApiRecommendationsUserIdParams = {
type?: string;
topN?: number;
};

export type GetApiRecommendationsAlbumAlbumIdParams = {
topN?: number;
};

export type GetApiReviewsAlbumIdParams = {
page?: number;
pageSize?: number;
sort?: string;
};

