/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * tunerate-api
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AlbumDto,
  GetApiAlbumsParams,
  GetApiAlbumsSearchParams,
  GetApiRecommendationUserIdParams,
  GetApiReviewsAlbumIdParams,
  ReviewDto
} from './tunerateApi.schemas';

import { axiosInstance } from '../axiosInstance';
import type { ErrorType , BodyType } from '../axiosInstance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getApiAlbums = (
    params?: GetApiAlbumsParams,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `/api/Albums`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiAlbumsQueryKey = (params?: GetApiAlbumsParams,) => {
    return [
    `/api/Albums`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiAlbumsQueryOptions = <TData = Awaited<ReturnType<typeof getApiAlbums>>, TError = ErrorType<unknown>>(params?: GetApiAlbumsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAlbums>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAlbumsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAlbums>>> = ({ signal }) => getApiAlbums(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAlbums>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAlbumsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAlbums>>>
export type GetApiAlbumsQueryError = ErrorType<unknown>


export function useGetApiAlbums<TData = Awaited<ReturnType<typeof getApiAlbums>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiAlbumsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAlbums>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAlbums>>,
          TError,
          Awaited<ReturnType<typeof getApiAlbums>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAlbums<TData = Awaited<ReturnType<typeof getApiAlbums>>, TError = ErrorType<unknown>>(
 params?: GetApiAlbumsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAlbums>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAlbums>>,
          TError,
          Awaited<ReturnType<typeof getApiAlbums>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAlbums<TData = Awaited<ReturnType<typeof getApiAlbums>>, TError = ErrorType<unknown>>(
 params?: GetApiAlbumsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAlbums>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAlbums<TData = Awaited<ReturnType<typeof getApiAlbums>>, TError = ErrorType<unknown>>(
 params?: GetApiAlbumsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAlbums>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAlbumsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const postApiAlbums = (
    albumDto: BodyType<AlbumDto>,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `/api/Albums`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: albumDto, signal
    },
      options);
    }
  


export const getPostApiAlbumsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAlbums>>, TError,{data: BodyType<AlbumDto>}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAlbums>>, TError,{data: BodyType<AlbumDto>}, TContext> => {

const mutationKey = ['postApiAlbums'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAlbums>>, {data: BodyType<AlbumDto>}> = (props) => {
          const {data} = props ?? {};

          return  postApiAlbums(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAlbumsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAlbums>>>
    export type PostApiAlbumsMutationBody = BodyType<AlbumDto>
    export type PostApiAlbumsMutationError = ErrorType<unknown>

    export const usePostApiAlbums = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAlbums>>, TError,{data: BodyType<AlbumDto>}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAlbums>>,
        TError,
        {data: BodyType<AlbumDto>},
        TContext
      > => {

      const mutationOptions = getPostApiAlbumsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getApiAlbumsAll = (
    
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `/api/Albums/all`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiAlbumsAllQueryKey = () => {
    return [
    `/api/Albums/all`
    ] as const;
    }

    
export const getGetApiAlbumsAllQueryOptions = <TData = Awaited<ReturnType<typeof getApiAlbumsAll>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAlbumsAll>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAlbumsAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAlbumsAll>>> = ({ signal }) => getApiAlbumsAll(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAlbumsAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAlbumsAllQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAlbumsAll>>>
export type GetApiAlbumsAllQueryError = ErrorType<unknown>


export function useGetApiAlbumsAll<TData = Awaited<ReturnType<typeof getApiAlbumsAll>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAlbumsAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAlbumsAll>>,
          TError,
          Awaited<ReturnType<typeof getApiAlbumsAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAlbumsAll<TData = Awaited<ReturnType<typeof getApiAlbumsAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAlbumsAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAlbumsAll>>,
          TError,
          Awaited<ReturnType<typeof getApiAlbumsAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAlbumsAll<TData = Awaited<ReturnType<typeof getApiAlbumsAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAlbumsAll>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAlbumsAll<TData = Awaited<ReturnType<typeof getApiAlbumsAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAlbumsAll>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAlbumsAllQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getApiAlbumsSearch = (
    params?: GetApiAlbumsSearchParams,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `/api/Albums/search`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiAlbumsSearchQueryKey = (params?: GetApiAlbumsSearchParams,) => {
    return [
    `/api/Albums/search`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiAlbumsSearchQueryOptions = <TData = Awaited<ReturnType<typeof getApiAlbumsSearch>>, TError = ErrorType<unknown>>(params?: GetApiAlbumsSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAlbumsSearch>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAlbumsSearchQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAlbumsSearch>>> = ({ signal }) => getApiAlbumsSearch(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAlbumsSearch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAlbumsSearchQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAlbumsSearch>>>
export type GetApiAlbumsSearchQueryError = ErrorType<unknown>


export function useGetApiAlbumsSearch<TData = Awaited<ReturnType<typeof getApiAlbumsSearch>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiAlbumsSearchParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAlbumsSearch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAlbumsSearch>>,
          TError,
          Awaited<ReturnType<typeof getApiAlbumsSearch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAlbumsSearch<TData = Awaited<ReturnType<typeof getApiAlbumsSearch>>, TError = ErrorType<unknown>>(
 params?: GetApiAlbumsSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAlbumsSearch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAlbumsSearch>>,
          TError,
          Awaited<ReturnType<typeof getApiAlbumsSearch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAlbumsSearch<TData = Awaited<ReturnType<typeof getApiAlbumsSearch>>, TError = ErrorType<unknown>>(
 params?: GetApiAlbumsSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAlbumsSearch>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAlbumsSearch<TData = Awaited<ReturnType<typeof getApiAlbumsSearch>>, TError = ErrorType<unknown>>(
 params?: GetApiAlbumsSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAlbumsSearch>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAlbumsSearchQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getApiAlbumsId = (
    id: string,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `/api/Albums/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiAlbumsIdQueryKey = (id?: string,) => {
    return [
    `/api/Albums/${id}`
    ] as const;
    }

    
export const getGetApiAlbumsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiAlbumsId>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAlbumsId>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAlbumsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAlbumsId>>> = ({ signal }) => getApiAlbumsId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAlbumsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAlbumsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAlbumsId>>>
export type GetApiAlbumsIdQueryError = ErrorType<unknown>


export function useGetApiAlbumsId<TData = Awaited<ReturnType<typeof getApiAlbumsId>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAlbumsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAlbumsId>>,
          TError,
          Awaited<ReturnType<typeof getApiAlbumsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAlbumsId<TData = Awaited<ReturnType<typeof getApiAlbumsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAlbumsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAlbumsId>>,
          TError,
          Awaited<ReturnType<typeof getApiAlbumsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAlbumsId<TData = Awaited<ReturnType<typeof getApiAlbumsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAlbumsId>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAlbumsId<TData = Awaited<ReturnType<typeof getApiAlbumsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAlbumsId>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAlbumsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getApiRecommendationUserId = (
    userId: string,
    params?: GetApiRecommendationUserIdParams,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `/api/Recommendation/${userId}`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiRecommendationUserIdQueryKey = (userId?: string,
    params?: GetApiRecommendationUserIdParams,) => {
    return [
    `/api/Recommendation/${userId}`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiRecommendationUserIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiRecommendationUserId>>, TError = ErrorType<unknown>>(userId: string,
    params?: GetApiRecommendationUserIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiRecommendationUserId>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiRecommendationUserIdQueryKey(userId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiRecommendationUserId>>> = ({ signal }) => getApiRecommendationUserId(userId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiRecommendationUserId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiRecommendationUserIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiRecommendationUserId>>>
export type GetApiRecommendationUserIdQueryError = ErrorType<unknown>


export function useGetApiRecommendationUserId<TData = Awaited<ReturnType<typeof getApiRecommendationUserId>>, TError = ErrorType<unknown>>(
 userId: string,
    params: undefined |  GetApiRecommendationUserIdParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiRecommendationUserId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiRecommendationUserId>>,
          TError,
          Awaited<ReturnType<typeof getApiRecommendationUserId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiRecommendationUserId<TData = Awaited<ReturnType<typeof getApiRecommendationUserId>>, TError = ErrorType<unknown>>(
 userId: string,
    params?: GetApiRecommendationUserIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiRecommendationUserId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiRecommendationUserId>>,
          TError,
          Awaited<ReturnType<typeof getApiRecommendationUserId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiRecommendationUserId<TData = Awaited<ReturnType<typeof getApiRecommendationUserId>>, TError = ErrorType<unknown>>(
 userId: string,
    params?: GetApiRecommendationUserIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiRecommendationUserId>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiRecommendationUserId<TData = Awaited<ReturnType<typeof getApiRecommendationUserId>>, TError = ErrorType<unknown>>(
 userId: string,
    params?: GetApiRecommendationUserIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiRecommendationUserId>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiRecommendationUserIdQueryOptions(userId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getApiReviewsAlbumId = (
    albumId: string,
    params?: GetApiReviewsAlbumIdParams,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `/api/Reviews/${albumId}`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiReviewsAlbumIdQueryKey = (albumId?: string,
    params?: GetApiReviewsAlbumIdParams,) => {
    return [
    `/api/Reviews/${albumId}`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiReviewsAlbumIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiReviewsAlbumId>>, TError = ErrorType<unknown>>(albumId: string,
    params?: GetApiReviewsAlbumIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReviewsAlbumId>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiReviewsAlbumIdQueryKey(albumId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiReviewsAlbumId>>> = ({ signal }) => getApiReviewsAlbumId(albumId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(albumId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiReviewsAlbumId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiReviewsAlbumIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiReviewsAlbumId>>>
export type GetApiReviewsAlbumIdQueryError = ErrorType<unknown>


export function useGetApiReviewsAlbumId<TData = Awaited<ReturnType<typeof getApiReviewsAlbumId>>, TError = ErrorType<unknown>>(
 albumId: string,
    params: undefined |  GetApiReviewsAlbumIdParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReviewsAlbumId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiReviewsAlbumId>>,
          TError,
          Awaited<ReturnType<typeof getApiReviewsAlbumId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiReviewsAlbumId<TData = Awaited<ReturnType<typeof getApiReviewsAlbumId>>, TError = ErrorType<unknown>>(
 albumId: string,
    params?: GetApiReviewsAlbumIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReviewsAlbumId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiReviewsAlbumId>>,
          TError,
          Awaited<ReturnType<typeof getApiReviewsAlbumId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiReviewsAlbumId<TData = Awaited<ReturnType<typeof getApiReviewsAlbumId>>, TError = ErrorType<unknown>>(
 albumId: string,
    params?: GetApiReviewsAlbumIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReviewsAlbumId>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiReviewsAlbumId<TData = Awaited<ReturnType<typeof getApiReviewsAlbumId>>, TError = ErrorType<unknown>>(
 albumId: string,
    params?: GetApiReviewsAlbumIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReviewsAlbumId>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiReviewsAlbumIdQueryOptions(albumId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const postApiReviewsAlbumId = (
    albumId: string,
    reviewDto: BodyType<ReviewDto>,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `/api/Reviews/${albumId}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: reviewDto, signal
    },
      options);
    }
  


export const getPostApiReviewsAlbumIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiReviewsAlbumId>>, TError,{albumId: string;data: BodyType<ReviewDto>}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiReviewsAlbumId>>, TError,{albumId: string;data: BodyType<ReviewDto>}, TContext> => {

const mutationKey = ['postApiReviewsAlbumId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiReviewsAlbumId>>, {albumId: string;data: BodyType<ReviewDto>}> = (props) => {
          const {albumId,data} = props ?? {};

          return  postApiReviewsAlbumId(albumId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiReviewsAlbumIdMutationResult = NonNullable<Awaited<ReturnType<typeof postApiReviewsAlbumId>>>
    export type PostApiReviewsAlbumIdMutationBody = BodyType<ReviewDto>
    export type PostApiReviewsAlbumIdMutationError = ErrorType<unknown>

    export const usePostApiReviewsAlbumId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiReviewsAlbumId>>, TError,{albumId: string;data: BodyType<ReviewDto>}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiReviewsAlbumId>>,
        TError,
        {albumId: string;data: BodyType<ReviewDto>},
        TContext
      > => {

      const mutationOptions = getPostApiReviewsAlbumIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const putApiReviewsReviewId = (
    reviewId: string,
    reviewDto: BodyType<ReviewDto>,
 options?: SecondParameter<typeof axiosInstance>,) => {
      
      
      return axiosInstance<void>(
      {url: `/api/Reviews/${reviewId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: reviewDto
    },
      options);
    }
  


export const getPutApiReviewsReviewIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiReviewsReviewId>>, TError,{reviewId: string;data: BodyType<ReviewDto>}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiReviewsReviewId>>, TError,{reviewId: string;data: BodyType<ReviewDto>}, TContext> => {

const mutationKey = ['putApiReviewsReviewId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiReviewsReviewId>>, {reviewId: string;data: BodyType<ReviewDto>}> = (props) => {
          const {reviewId,data} = props ?? {};

          return  putApiReviewsReviewId(reviewId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiReviewsReviewIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiReviewsReviewId>>>
    export type PutApiReviewsReviewIdMutationBody = BodyType<ReviewDto>
    export type PutApiReviewsReviewIdMutationError = ErrorType<unknown>

    export const usePutApiReviewsReviewId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiReviewsReviewId>>, TError,{reviewId: string;data: BodyType<ReviewDto>}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiReviewsReviewId>>,
        TError,
        {reviewId: string;data: BodyType<ReviewDto>},
        TContext
      > => {

      const mutationOptions = getPutApiReviewsReviewIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const deleteApiReviewsReviewId = (
    reviewId: string,
 options?: SecondParameter<typeof axiosInstance>,) => {
      
      
      return axiosInstance<void>(
      {url: `/api/Reviews/${reviewId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiReviewsReviewIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiReviewsReviewId>>, TError,{reviewId: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiReviewsReviewId>>, TError,{reviewId: string}, TContext> => {

const mutationKey = ['deleteApiReviewsReviewId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiReviewsReviewId>>, {reviewId: string}> = (props) => {
          const {reviewId} = props ?? {};

          return  deleteApiReviewsReviewId(reviewId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiReviewsReviewIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiReviewsReviewId>>>
    
    export type DeleteApiReviewsReviewIdMutationError = ErrorType<unknown>

    export const useDeleteApiReviewsReviewId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiReviewsReviewId>>, TError,{reviewId: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiReviewsReviewId>>,
        TError,
        {reviewId: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiReviewsReviewIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const postApiUserAlbums = (
    albumDto: BodyType<AlbumDto>,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `/api/UserAlbums`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: albumDto, signal
    },
      options);
    }
  


export const getPostApiUserAlbumsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiUserAlbums>>, TError,{data: BodyType<AlbumDto>}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiUserAlbums>>, TError,{data: BodyType<AlbumDto>}, TContext> => {

const mutationKey = ['postApiUserAlbums'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiUserAlbums>>, {data: BodyType<AlbumDto>}> = (props) => {
          const {data} = props ?? {};

          return  postApiUserAlbums(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiUserAlbumsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiUserAlbums>>>
    export type PostApiUserAlbumsMutationBody = BodyType<AlbumDto>
    export type PostApiUserAlbumsMutationError = ErrorType<unknown>

    export const usePostApiUserAlbums = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiUserAlbums>>, TError,{data: BodyType<AlbumDto>}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiUserAlbums>>,
        TError,
        {data: BodyType<AlbumDto>},
        TContext
      > => {

      const mutationOptions = getPostApiUserAlbumsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getApiUserAlbums = (
    
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `/api/UserAlbums`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiUserAlbumsQueryKey = () => {
    return [
    `/api/UserAlbums`
    ] as const;
    }

    
export const getGetApiUserAlbumsQueryOptions = <TData = Awaited<ReturnType<typeof getApiUserAlbums>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUserAlbums>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiUserAlbumsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiUserAlbums>>> = ({ signal }) => getApiUserAlbums(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiUserAlbums>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiUserAlbumsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiUserAlbums>>>
export type GetApiUserAlbumsQueryError = ErrorType<unknown>


export function useGetApiUserAlbums<TData = Awaited<ReturnType<typeof getApiUserAlbums>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUserAlbums>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUserAlbums>>,
          TError,
          Awaited<ReturnType<typeof getApiUserAlbums>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiUserAlbums<TData = Awaited<ReturnType<typeof getApiUserAlbums>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUserAlbums>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUserAlbums>>,
          TError,
          Awaited<ReturnType<typeof getApiUserAlbums>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiUserAlbums<TData = Awaited<ReturnType<typeof getApiUserAlbums>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUserAlbums>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiUserAlbums<TData = Awaited<ReturnType<typeof getApiUserAlbums>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUserAlbums>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiUserAlbumsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const deleteApiUserAlbumsAlbumId = (
    albumId: string,
 options?: SecondParameter<typeof axiosInstance>,) => {
      
      
      return axiosInstance<void>(
      {url: `/api/UserAlbums/${albumId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiUserAlbumsAlbumIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiUserAlbumsAlbumId>>, TError,{albumId: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiUserAlbumsAlbumId>>, TError,{albumId: string}, TContext> => {

const mutationKey = ['deleteApiUserAlbumsAlbumId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiUserAlbumsAlbumId>>, {albumId: string}> = (props) => {
          const {albumId} = props ?? {};

          return  deleteApiUserAlbumsAlbumId(albumId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiUserAlbumsAlbumIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiUserAlbumsAlbumId>>>
    
    export type DeleteApiUserAlbumsAlbumIdMutationError = ErrorType<unknown>

    export const useDeleteApiUserAlbumsAlbumId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiUserAlbumsAlbumId>>, TError,{albumId: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiUserAlbumsAlbumId>>,
        TError,
        {albumId: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiUserAlbumsAlbumIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getApiUsers = (
    
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `/api/Users`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiUsersQueryKey = () => {
    return [
    `/api/Users`
    ] as const;
    }

    
export const getGetApiUsersQueryOptions = <TData = Awaited<ReturnType<typeof getApiUsers>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiUsersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiUsers>>> = ({ signal }) => getApiUsers(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getApiUsers>>>
export type GetApiUsersQueryError = ErrorType<unknown>


export function useGetApiUsers<TData = Awaited<ReturnType<typeof getApiUsers>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUsers>>,
          TError,
          Awaited<ReturnType<typeof getApiUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiUsers<TData = Awaited<ReturnType<typeof getApiUsers>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUsers>>,
          TError,
          Awaited<ReturnType<typeof getApiUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiUsers<TData = Awaited<ReturnType<typeof getApiUsers>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiUsers<TData = Awaited<ReturnType<typeof getApiUsers>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiUsersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getApiUsersByAuth0idAuth0Id = (
    auth0Id: string,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `/api/Users/by-auth0id/${auth0Id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiUsersByAuth0idAuth0IdQueryKey = (auth0Id?: string,) => {
    return [
    `/api/Users/by-auth0id/${auth0Id}`
    ] as const;
    }

    
export const getGetApiUsersByAuth0idAuth0IdQueryOptions = <TData = Awaited<ReturnType<typeof getApiUsersByAuth0idAuth0Id>>, TError = ErrorType<unknown>>(auth0Id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersByAuth0idAuth0Id>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiUsersByAuth0idAuth0IdQueryKey(auth0Id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiUsersByAuth0idAuth0Id>>> = ({ signal }) => getApiUsersByAuth0idAuth0Id(auth0Id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(auth0Id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiUsersByAuth0idAuth0Id>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiUsersByAuth0idAuth0IdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiUsersByAuth0idAuth0Id>>>
export type GetApiUsersByAuth0idAuth0IdQueryError = ErrorType<unknown>


export function useGetApiUsersByAuth0idAuth0Id<TData = Awaited<ReturnType<typeof getApiUsersByAuth0idAuth0Id>>, TError = ErrorType<unknown>>(
 auth0Id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersByAuth0idAuth0Id>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUsersByAuth0idAuth0Id>>,
          TError,
          Awaited<ReturnType<typeof getApiUsersByAuth0idAuth0Id>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiUsersByAuth0idAuth0Id<TData = Awaited<ReturnType<typeof getApiUsersByAuth0idAuth0Id>>, TError = ErrorType<unknown>>(
 auth0Id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersByAuth0idAuth0Id>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUsersByAuth0idAuth0Id>>,
          TError,
          Awaited<ReturnType<typeof getApiUsersByAuth0idAuth0Id>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiUsersByAuth0idAuth0Id<TData = Awaited<ReturnType<typeof getApiUsersByAuth0idAuth0Id>>, TError = ErrorType<unknown>>(
 auth0Id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersByAuth0idAuth0Id>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiUsersByAuth0idAuth0Id<TData = Awaited<ReturnType<typeof getApiUsersByAuth0idAuth0Id>>, TError = ErrorType<unknown>>(
 auth0Id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersByAuth0idAuth0Id>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiUsersByAuth0idAuth0IdQueryOptions(auth0Id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const postApiUsersSync = (
    
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `/api/Users/sync`, method: 'POST', signal
    },
      options);
    }
  


export const getPostApiUsersSyncMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiUsersSync>>, TError,void, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiUsersSync>>, TError,void, TContext> => {

const mutationKey = ['postApiUsersSync'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiUsersSync>>, void> = () => {
          

          return  postApiUsersSync(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiUsersSyncMutationResult = NonNullable<Awaited<ReturnType<typeof postApiUsersSync>>>
    
    export type PostApiUsersSyncMutationError = ErrorType<unknown>

    export const usePostApiUsersSync = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiUsersSync>>, TError,void, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiUsersSync>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getPostApiUsersSyncMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
