/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * tunerate-api
 * OpenAPI spec version: 1.0
 */
export interface AlbumDto {
  /** @nullable */
  title?: string | null;
  /** @nullable */
  artist?: string | null;
  artistId?: string;
  /** @nullable */
  releaseDate?: string | null;
  /** @nullable */
  externalId?: string | null;
  /** @nullable */
  coverUrl?: string | null;
}

export type GetApiAlbumsSearchParams = {
query?: string;
};

