/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * tunerate-api
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AlbumDto,
  GetApiAlbumsSearchParams,
  ReviewDto
} from './tunerateApi.schemas';

import { axiosInstance } from '../axiosInstance';
import type { ErrorType , BodyType } from '../axiosInstance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getApiAlbumsSearch = (
    params?: GetApiAlbumsSearchParams,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `/api/Albums/search`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiAlbumsSearchQueryKey = (params?: GetApiAlbumsSearchParams,) => {
    return [
    `/api/Albums/search`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiAlbumsSearchQueryOptions = <TData = Awaited<ReturnType<typeof getApiAlbumsSearch>>, TError = ErrorType<unknown>>(params?: GetApiAlbumsSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAlbumsSearch>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAlbumsSearchQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAlbumsSearch>>> = ({ signal }) => getApiAlbumsSearch(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAlbumsSearch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAlbumsSearchQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAlbumsSearch>>>
export type GetApiAlbumsSearchQueryError = ErrorType<unknown>


export function useGetApiAlbumsSearch<TData = Awaited<ReturnType<typeof getApiAlbumsSearch>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiAlbumsSearchParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAlbumsSearch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAlbumsSearch>>,
          TError,
          Awaited<ReturnType<typeof getApiAlbumsSearch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAlbumsSearch<TData = Awaited<ReturnType<typeof getApiAlbumsSearch>>, TError = ErrorType<unknown>>(
 params?: GetApiAlbumsSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAlbumsSearch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAlbumsSearch>>,
          TError,
          Awaited<ReturnType<typeof getApiAlbumsSearch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAlbumsSearch<TData = Awaited<ReturnType<typeof getApiAlbumsSearch>>, TError = ErrorType<unknown>>(
 params?: GetApiAlbumsSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAlbumsSearch>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAlbumsSearch<TData = Awaited<ReturnType<typeof getApiAlbumsSearch>>, TError = ErrorType<unknown>>(
 params?: GetApiAlbumsSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAlbumsSearch>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAlbumsSearchQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getApiAlbumsId = (
    id: string,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `/api/Albums/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiAlbumsIdQueryKey = (id?: string,) => {
    return [
    `/api/Albums/${id}`
    ] as const;
    }

    
export const getGetApiAlbumsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiAlbumsId>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAlbumsId>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAlbumsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAlbumsId>>> = ({ signal }) => getApiAlbumsId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAlbumsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAlbumsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAlbumsId>>>
export type GetApiAlbumsIdQueryError = ErrorType<unknown>


export function useGetApiAlbumsId<TData = Awaited<ReturnType<typeof getApiAlbumsId>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAlbumsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAlbumsId>>,
          TError,
          Awaited<ReturnType<typeof getApiAlbumsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAlbumsId<TData = Awaited<ReturnType<typeof getApiAlbumsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAlbumsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAlbumsId>>,
          TError,
          Awaited<ReturnType<typeof getApiAlbumsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAlbumsId<TData = Awaited<ReturnType<typeof getApiAlbumsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAlbumsId>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAlbumsId<TData = Awaited<ReturnType<typeof getApiAlbumsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAlbumsId>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAlbumsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getApiAlbumsIdReviews = (
    id: string,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `/api/Albums/${id}/reviews`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiAlbumsIdReviewsQueryKey = (id?: string,) => {
    return [
    `/api/Albums/${id}/reviews`
    ] as const;
    }

    
export const getGetApiAlbumsIdReviewsQueryOptions = <TData = Awaited<ReturnType<typeof getApiAlbumsIdReviews>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAlbumsIdReviews>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAlbumsIdReviewsQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAlbumsIdReviews>>> = ({ signal }) => getApiAlbumsIdReviews(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAlbumsIdReviews>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAlbumsIdReviewsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAlbumsIdReviews>>>
export type GetApiAlbumsIdReviewsQueryError = ErrorType<unknown>


export function useGetApiAlbumsIdReviews<TData = Awaited<ReturnType<typeof getApiAlbumsIdReviews>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAlbumsIdReviews>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAlbumsIdReviews>>,
          TError,
          Awaited<ReturnType<typeof getApiAlbumsIdReviews>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAlbumsIdReviews<TData = Awaited<ReturnType<typeof getApiAlbumsIdReviews>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAlbumsIdReviews>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAlbumsIdReviews>>,
          TError,
          Awaited<ReturnType<typeof getApiAlbumsIdReviews>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAlbumsIdReviews<TData = Awaited<ReturnType<typeof getApiAlbumsIdReviews>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAlbumsIdReviews>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAlbumsIdReviews<TData = Awaited<ReturnType<typeof getApiAlbumsIdReviews>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAlbumsIdReviews>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAlbumsIdReviewsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const postApiAlbumsIdReviews = (
    id: string,
    reviewDto: BodyType<ReviewDto>,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `/api/Albums/${id}/reviews`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: reviewDto, signal
    },
      options);
    }
  


export const getPostApiAlbumsIdReviewsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAlbumsIdReviews>>, TError,{id: string;data: BodyType<ReviewDto>}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAlbumsIdReviews>>, TError,{id: string;data: BodyType<ReviewDto>}, TContext> => {

const mutationKey = ['postApiAlbumsIdReviews'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAlbumsIdReviews>>, {id: string;data: BodyType<ReviewDto>}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiAlbumsIdReviews(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAlbumsIdReviewsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAlbumsIdReviews>>>
    export type PostApiAlbumsIdReviewsMutationBody = BodyType<ReviewDto>
    export type PostApiAlbumsIdReviewsMutationError = ErrorType<unknown>

    export const usePostApiAlbumsIdReviews = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAlbumsIdReviews>>, TError,{id: string;data: BodyType<ReviewDto>}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAlbumsIdReviews>>,
        TError,
        {id: string;data: BodyType<ReviewDto>},
        TContext
      > => {

      const mutationOptions = getPostApiAlbumsIdReviewsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const postApiUserAlbums = (
    albumDto: BodyType<AlbumDto>,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `/api/UserAlbums`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: albumDto, signal
    },
      options);
    }
  


export const getPostApiUserAlbumsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiUserAlbums>>, TError,{data: BodyType<AlbumDto>}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiUserAlbums>>, TError,{data: BodyType<AlbumDto>}, TContext> => {

const mutationKey = ['postApiUserAlbums'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiUserAlbums>>, {data: BodyType<AlbumDto>}> = (props) => {
          const {data} = props ?? {};

          return  postApiUserAlbums(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiUserAlbumsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiUserAlbums>>>
    export type PostApiUserAlbumsMutationBody = BodyType<AlbumDto>
    export type PostApiUserAlbumsMutationError = ErrorType<unknown>

    export const usePostApiUserAlbums = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiUserAlbums>>, TError,{data: BodyType<AlbumDto>}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiUserAlbums>>,
        TError,
        {data: BodyType<AlbumDto>},
        TContext
      > => {

      const mutationOptions = getPostApiUserAlbumsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getApiUserAlbums = (
    
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `/api/UserAlbums`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiUserAlbumsQueryKey = () => {
    return [
    `/api/UserAlbums`
    ] as const;
    }

    
export const getGetApiUserAlbumsQueryOptions = <TData = Awaited<ReturnType<typeof getApiUserAlbums>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUserAlbums>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiUserAlbumsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiUserAlbums>>> = ({ signal }) => getApiUserAlbums(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiUserAlbums>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiUserAlbumsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiUserAlbums>>>
export type GetApiUserAlbumsQueryError = ErrorType<unknown>


export function useGetApiUserAlbums<TData = Awaited<ReturnType<typeof getApiUserAlbums>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUserAlbums>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUserAlbums>>,
          TError,
          Awaited<ReturnType<typeof getApiUserAlbums>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiUserAlbums<TData = Awaited<ReturnType<typeof getApiUserAlbums>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUserAlbums>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUserAlbums>>,
          TError,
          Awaited<ReturnType<typeof getApiUserAlbums>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiUserAlbums<TData = Awaited<ReturnType<typeof getApiUserAlbums>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUserAlbums>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiUserAlbums<TData = Awaited<ReturnType<typeof getApiUserAlbums>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUserAlbums>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiUserAlbumsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const deleteApiUserAlbumsAlbumId = (
    albumId: string,
 options?: SecondParameter<typeof axiosInstance>,) => {
      
      
      return axiosInstance<void>(
      {url: `/api/UserAlbums/${albumId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiUserAlbumsAlbumIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiUserAlbumsAlbumId>>, TError,{albumId: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiUserAlbumsAlbumId>>, TError,{albumId: string}, TContext> => {

const mutationKey = ['deleteApiUserAlbumsAlbumId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiUserAlbumsAlbumId>>, {albumId: string}> = (props) => {
          const {albumId} = props ?? {};

          return  deleteApiUserAlbumsAlbumId(albumId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiUserAlbumsAlbumIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiUserAlbumsAlbumId>>>
    
    export type DeleteApiUserAlbumsAlbumIdMutationError = ErrorType<unknown>

    export const useDeleteApiUserAlbumsAlbumId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiUserAlbumsAlbumId>>, TError,{albumId: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiUserAlbumsAlbumId>>,
        TError,
        {albumId: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiUserAlbumsAlbumIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const postApiUsersSync = (
    
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `/api/Users/sync`, method: 'POST', signal
    },
      options);
    }
  


export const getPostApiUsersSyncMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiUsersSync>>, TError,void, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiUsersSync>>, TError,void, TContext> => {

const mutationKey = ['postApiUsersSync'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiUsersSync>>, void> = () => {
          

          return  postApiUsersSync(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiUsersSyncMutationResult = NonNullable<Awaited<ReturnType<typeof postApiUsersSync>>>
    
    export type PostApiUsersSyncMutationError = ErrorType<unknown>

    export const usePostApiUsersSync = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiUsersSync>>, TError,void, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiUsersSync>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getPostApiUsersSyncMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
